services:
  - type: web
    name: codelab
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    plan: free
    autoDeploy: true 